"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-28 09:16:38.004979

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_state",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_bot_state")),
    )
    op.create_index(op.f("ix_bot_state_expires_at"), "bot_state", ["expires_at"], unique=False)
    op.create_table(
        "brands",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column(
            "base_authenticity_risk",
            sa.Numeric(precision=4, scale=3),
            server_default=sa.text("0.3"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_authenticity_risk IS NULL OR (base_authenticity_risk >= 0 AND base_authenticity_risk <= 1)",
            name=op.f("ck_brands_base_authenticity_risk_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("name", name=op.f("uq_brands_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_brands_slug")),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("level", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("in_scope", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("priority", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "config_versions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "name", sa.String(length=64), server_default=sa.text("'default'"), nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "kind IN ('deal_rules', 'fees', 'conditions', 'sizes', 'market', 'authenticity', 'identification', 'price_guide')",
            name=op.f("ck_config_versions_kind_valid"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_config_versions_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_config_versions")),
        sa.UniqueConstraint(
            "kind", "name", "version", name=op.f("uq_config_versions_kind_name_version")
        ),
    )
    op.create_index(
        "uq_config_versions_one_active",
        "config_versions",
        ["kind", "name"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "fx_rates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("base", sa.String(length=3), nullable=False),
        sa.Column("quote", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column(
            "source", sa.String(length=50), server_default=sa.text("'manual'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base IS NULL OR base ~ '^[A-Z]{3}$'", name=op.f("ck_fx_rates_base_iso")
        ),
        sa.CheckConstraint(
            "quote IS NULL OR quote ~ '^[A-Z]{3}$'", name=op.f("ck_fx_rates_quote_iso")
        ),
        sa.CheckConstraint("rate > 0", name=op.f("ck_fx_rates_rate_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_rates")),
        sa.UniqueConstraint("base", "quote", "as_of", name=op.f("uq_fx_rates_base_quote_as_of")),
    )
    op.create_table(
        "marketplaces",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_marketplaces")),
    )
    op.create_table(
        "task_failures",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("task_name", sa.String(length=200), nullable=False),
        sa.Column("task_id", sa.String(length=100), nullable=True),
        sa.Column(
            "args",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.String(length=1000), nullable=False),
        sa.Column("retries", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "failed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_failures")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), server_default=sa.text("'owner'"), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('owner', 'viewer')", name=op.f("ck_users_role_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_users_telegram_user_id")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "scopes",
            postgresql.ARRAY(sa.String(length=32)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_keys_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_label", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=50), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_log_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_entity", "audit_log", ["entity_type", "entity_id"], unique=False)
    op.create_table(
        "brand_aliases",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("brand_id", sa.BigInteger(), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("alias_normalised", sa.String(length=100), nullable=False),
        sa.Column("is_negative", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_brand_aliases_brand_id_brands"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_aliases")),
        sa.UniqueConstraint(
            "brand_id", "alias_normalised", name=op.f("uq_brand_aliases_brand_id_alias_normalised")
        ),
    )
    op.create_index(
        op.f("ix_brand_aliases_alias_normalised"),
        "brand_aliases",
        ["alias_normalised"],
        unique=False,
    )
    op.create_index(op.f("ix_brand_aliases_brand_id"), "brand_aliases", ["brand_id"], unique=False)
    op.create_table(
        "category_aliases",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("alias_normalised", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_category_aliases_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category_aliases")),
        sa.UniqueConstraint("alias_normalised", name=op.f("uq_category_aliases_alias_normalised")),
    )
    op.create_index(
        op.f("ix_category_aliases_category_id"), "category_aliases", ["category_id"], unique=False
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_total", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_skipped", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_summary", sa.String(length=1000), nullable=True),
        sa.Column(
            "report",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('listings_csv', 'sales_csv', 'api_batch', 'fixture')",
            name=op.f("ck_ingestion_runs_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'ok', 'partial', 'failed')",
            name=op.f("ck_ingestion_runs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_ingestion_runs_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("brand_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("level", sa.String(length=32), nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("model_code", sa.String(length=50), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("season", sa.String(length=20), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("reference_retail_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("retail_currency", sa.String(length=3), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('model', 'product_line', 'brand_category_generic')",
            name=op.f("ck_products_level_valid"),
        ),
        sa.CheckConstraint(
            "retail_currency IS NULL OR retail_currency ~ '^[A-Z]{3}$'",
            name=op.f("ck_products_retail_currency_iso"),
        ),
        sa.CheckConstraint(
            "reference_retail_price IS NULL OR retail_currency IS NOT NULL",
            name=op.f("ck_products_retail_price_has_currency"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_products_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_products_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("brand_id", "slug", name=op.f("uq_products_brand_id_slug")),
    )
    op.create_index(
        "ix_products_brand_category", "products", ["brand_id", "category_id"], unique=False
    )
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(
        "uq_products_brand_model_code",
        "products",
        ["brand_id", "model_code"],
        unique=True,
        postgresql_where=sa.text("model_code IS NOT NULL"),
    )
    op.create_index(
        "uq_products_generic_per_brand_category",
        "products",
        ["brand_id", "category_id"],
        unique=True,
        postgresql_where=sa.text("level = 'brand_category_generic'"),
    )
    op.create_table(
        "sellers",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("external_seller_id", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("member_since", sa.Date(), nullable=True),
        sa.Column(
            "operator_flag", sa.String(length=10), server_default=sa.text("'none'"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "operator_flag IN ('none', 'trusted', 'blocked')",
            name=op.f("ck_sellers_operator_flag_valid"),
        ),
        sa.CheckConstraint(
            "rating IS NULL OR (rating >= 0 AND rating <= 5)", name=op.f("ck_sellers_rating_range")
        ),
        sa.CheckConstraint(
            "review_count IS NULL OR review_count >= 0",
            name=op.f("ck_sellers_review_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["marketplace"], ["marketplaces.code"], name=op.f("fk_sellers_marketplace_marketplaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sellers")),
        sa.UniqueConstraint(
            "marketplace",
            "external_seller_id",
            name=op.f("uq_sellers_marketplace_external_seller_id"),
        ),
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("seller_id", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("raw_brand", sa.String(length=100), nullable=True),
        sa.Column("raw_category", sa.String(length=100), nullable=True),
        sa.Column("raw_size", sa.String(length=50), nullable=True),
        sa.Column("raw_colour", sa.String(length=50), nullable=True),
        sa.Column("raw_condition", sa.String(length=50), nullable=True),
        sa.Column("brand_id", sa.BigInteger(), nullable=True),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("model_text", sa.String(length=200), nullable=True),
        sa.Column("size_normalised", sa.String(length=10), nullable=True),
        sa.Column("size_system", sa.String(length=20), nullable=True),
        sa.Column("is_kids", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("colour", sa.String(length=30), nullable=True),
        sa.Column("condition", sa.String(length=20), nullable=True),
        sa.Column("identification_method", sa.String(length=20), nullable=True),
        sa.Column("matched_product_id", sa.BigInteger(), nullable=True),
        sa.Column("match_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("listed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("possible_duplicate_of", sa.BigInteger(), nullable=True),
        sa.Column("submitted_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition IS NULL OR condition IN ('new_with_tags', 'new_without_tags', 'very_good', 'good', 'satisfactory')",
            name=op.f("ck_listings_condition_valid"),
        ),
        sa.CheckConstraint(
            "currency IS NULL OR currency ~ '^[A-Z]{3}$'", name=op.f("ck_listings_currency_iso")
        ),
        sa.CheckConstraint(
            "identification_method IS NULL OR identification_method IN ('rules', 'ai', 'rules+ai', 'mislabel_ai', 'manual')",
            name=op.f("ck_listings_identification_method_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('telegram', 'api', 'csv', 'fixture')", name=op.f("ck_listings_source_valid")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'reserved', 'sold', 'removed', 'unknown')",
            name=op.f("ck_listings_status_valid"),
        ),
        sa.CheckConstraint(
            "match_confidence IS NULL OR (match_confidence >= 0 AND match_confidence <= 1)",
            name=op.f("ck_listings_match_confidence_range"),
        ),
        sa.CheckConstraint(
            "price IS NULL OR currency IS NOT NULL", name=op.f("ck_listings_price_has_currency")
        ),
        sa.CheckConstraint("price IS NULL OR price > 0", name=op.f("ck_listings_price_positive")),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_listings_brand_id_brands"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_listings_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["marketplace"],
            ["marketplaces.code"],
            name=op.f("fk_listings_marketplace_marketplaces"),
        ),
        sa.ForeignKeyConstraint(
            ["matched_product_id"],
            ["products.id"],
            name=op.f("fk_listings_matched_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["possible_duplicate_of"],
            ["listings.id"],
            name=op.f("fk_listings_possible_duplicate_of_listings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["sellers.id"],
            name=op.f("fk_listings_seller_id_sellers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["users.id"],
            name=op.f("fk_listings_submitted_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
        sa.UniqueConstraint(
            "marketplace", "external_id", name=op.f("uq_listings_marketplace_external_id")
        ),
    )
    op.create_index(
        "ix_listings_active_first_seen",
        "listings",
        [sa.literal_column("first_seen_at DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_listings_brand_category", "listings", ["brand_id", "category_id"], unique=False
    )
    op.create_index(op.f("ix_listings_category_id"), "listings", ["category_id"], unique=False)
    op.create_index(
        op.f("ix_listings_matched_product_id"), "listings", ["matched_product_id"], unique=False
    )
    op.create_index(op.f("ix_listings_seller_id"), "listings", ["seller_id"], unique=False)
    op.create_index(
        "ix_listings_status_first_seen",
        "listings",
        ["status", sa.literal_column("first_seen_at DESC")],
        unique=False,
    )
    op.create_table(
        "market_statistics",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("scope_level", sa.String(length=8), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=True),
        sa.Column("brand_id", sa.BigInteger(), nullable=True),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("size_normalised", sa.String(length=10), nullable=True),
        sa.Column("condition", sa.String(length=20), nullable=True),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("effective_sample_size", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("p10", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("p25", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("median", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("p75", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("p90", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("median_days_to_sale", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("sales_last_30d", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sales_last_90d", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "active_listings_observed", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("method_version", sa.String(length=20), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "currency IS NULL OR currency ~ '^[A-Z]{3}$'",
            name=op.f("ck_market_statistics_currency_iso"),
        ),
        sa.CheckConstraint(
            "scope_level IN ('L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'GUIDE')",
            name=op.f("ck_market_statistics_scope_level_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_market_statistics_brand_id_brands"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_market_statistics_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_market_statistics_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_statistics")),
    )
    op.create_index(
        "uq_market_statistics_scope",
        "market_statistics",
        [
            "scope_level",
            "product_id",
            "brand_id",
            "category_id",
            "size_normalised",
            "condition",
            "window_days",
            "currency",
        ],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "product_aliases",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.Column("alias_normalised", sa.String(length=200), nullable=False),
        sa.Column(
            "alias_type", sa.String(length=20), server_default=sa.text("'name'"), nullable=False
        ),
        sa.Column(
            "weight", sa.Numeric(precision=4, scale=3), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("source", sa.String(length=20), server_default=sa.text("'seed'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "alias_type IN ('name', 'model_code', 'nickname', 'misspelling')",
            name=op.f("ck_product_aliases_alias_type_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('seed', 'manual', 'learned')", name=op.f("ck_product_aliases_source_valid")
        ),
        sa.CheckConstraint(
            "weight IS NULL OR (weight >= 0 AND weight <= 1)",
            name=op.f("ck_product_aliases_weight_range"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_aliases_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_aliases")),
        sa.UniqueConstraint(
            "product_id",
            "alias_normalised",
            name=op.f("uq_product_aliases_product_id_alias_normalised"),
        ),
    )
    op.create_index(
        op.f("ix_product_aliases_alias_normalised"),
        "product_aliases",
        ["alias_normalised"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_aliases_product_id"), "product_aliases", ["product_id"], unique=False
    )
    op.create_table(
        "ai_requests",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=12, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("listing_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ok', 'error', 'timeout', 'invalid_response', 'budget_exceeded')",
            name=op.f("ck_ai_requests_status_valid"),
        ),
        sa.CheckConstraint(
            "cost_usd IS NULL OR cost_usd >= 0", name=op.f("ck_ai_requests_cost_usd_non_negative")
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name=op.f("ck_ai_requests_input_tokens_non_negative"),
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name=op.f("ck_ai_requests_output_tokens_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_ai_requests_listing_id_listings"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_requests")),
    )
    op.create_index(
        "ix_ai_requests_hash_purpose", "ai_requests", ["input_hash", "purpose"], unique=False
    )
    op.create_table(
        "listing_evaluations",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "trigger", sa.String(length=20), server_default=sa.text("'ingest'"), nullable=False
        ),
        sa.Column("pipeline_version", sa.String(length=20), nullable=False),
        sa.Column("config_version_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("price_at_evaluation", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("brand_id", sa.BigInteger(), nullable=True),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("product_id", sa.BigInteger(), nullable=True),
        sa.Column("identification_method", sa.String(length=20), nullable=True),
        sa.Column("identification_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("match_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("mislabel_flag", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("estimate_basis", sa.String(length=16), nullable=True),
        sa.Column("comp_level", sa.String(length=8), nullable=True),
        sa.Column("comp_sample_size", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "comp_effective_sample_size",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("quick_sale_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expected_sale_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("optimistic_sale_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("estimate_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("median_days_to_sale", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("liquidity_score", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("total_acquisition_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expected_selling_costs", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expected_profit", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expected_roi", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("max_purchase_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("authenticity_risk_score", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("authenticity_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column(
            "reason_codes",
            postgresql.ARRAY(sa.String(length=64)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ai_used", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "ai_cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "comp_level IS NULL OR comp_level IN ('L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'GUIDE')",
            name=op.f("ck_listing_evaluations_comp_level_valid"),
        ),
        sa.CheckConstraint(
            "currency IS NULL OR currency ~ '^[A-Z]{3}$'",
            name=op.f("ck_listing_evaluations_currency_iso"),
        ),
        sa.CheckConstraint(
            "decision IN ('high_priority', 'normal', 'review', 'rejected')",
            name=op.f("ck_listing_evaluations_decision_valid"),
        ),
        sa.CheckConstraint(
            "estimate_basis IS NULL OR estimate_basis IN ('comps', 'price_guide')",
            name=op.f("ck_listing_evaluations_estimate_basis_valid"),
        ),
        sa.CheckConstraint(
            "identification_method IS NULL OR identification_method IN ('rules', 'ai', 'rules+ai', 'mislabel_ai', 'manual')",
            name=op.f("ck_listing_evaluations_identification_method_valid"),
        ),
        sa.CheckConstraint(
            "trigger IN ('ingest', 'manual', 'price_change', 'config_change', 'backfill')",
            name=op.f("ck_listing_evaluations_trigger_valid"),
        ),
        sa.CheckConstraint(
            "authenticity_confidence IS NULL OR (authenticity_confidence >= 0 AND authenticity_confidence <= 1)",
            name=op.f("ck_listing_evaluations_authenticity_confidence_range"),
        ),
        sa.CheckConstraint(
            "authenticity_risk_score IS NULL OR (authenticity_risk_score >= 0 AND authenticity_risk_score <= 1)",
            name=op.f("ck_listing_evaluations_authenticity_risk_score_range"),
        ),
        sa.CheckConstraint(
            "estimate_confidence IS NULL OR (estimate_confidence >= 0 AND estimate_confidence <= 1)",
            name=op.f("ck_listing_evaluations_estimate_confidence_range"),
        ),
        sa.CheckConstraint(
            "identification_confidence IS NULL OR (identification_confidence >= 0 AND identification_confidence <= 1)",
            name=op.f("ck_listing_evaluations_identification_confidence_range"),
        ),
        sa.CheckConstraint(
            "liquidity_score IS NULL OR (liquidity_score >= 0 AND liquidity_score <= 1)",
            name=op.f("ck_listing_evaluations_liquidity_score_range"),
        ),
        sa.CheckConstraint(
            "match_confidence IS NULL OR (match_confidence >= 0 AND match_confidence <= 1)",
            name=op.f("ck_listing_evaluations_match_confidence_range"),
        ),
        sa.CheckConstraint(
            "max_purchase_price IS NULL OR max_purchase_price >= 0",
            name=op.f("ck_listing_evaluations_max_purchase_price_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_listing_evaluations_brand_id_brands"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_listing_evaluations_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_evaluations_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_listing_evaluations_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_evaluations")),
    )
    op.create_index(
        "ix_listing_evaluations_decision_evaluated",
        "listing_evaluations",
        ["decision", sa.literal_column("evaluated_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_listing_evaluations_listing_evaluated",
        "listing_evaluations",
        ["listing_id", sa.literal_column("evaluated_at DESC")],
        unique=False,
    )
    op.create_table(
        "listing_images",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=True),
        sa.Column("telegram_file_id", sa.String(length=200), nullable=True),
        sa.Column("telegram_file_unique_id", sa.String(length=100), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("phash", sa.String(length=16), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=50), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('upload', 'telegram')", name=op.f("ck_listing_images_source_valid")
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_listing_images_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_images_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_images")),
        sa.UniqueConstraint(
            "listing_id", "position", name=op.f("uq_listing_images_listing_id_position")
        ),
        sa.UniqueConstraint(
            "listing_id", "sha256", name=op.f("uq_listing_images_listing_id_sha256")
        ),
    )
    op.create_index(
        op.f("ix_listing_images_listing_id"), "listing_images", ["listing_id"], unique=False
    )
    op.create_index(op.f("ix_listing_images_phash"), "listing_images", ["phash"], unique=False)
    op.create_table(
        "listing_status_history",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.CheckConstraint(
            "from_status IS NULL OR from_status IN ('active', 'reserved', 'sold', 'removed', 'unknown')",
            name=op.f("ck_listing_status_history_from_status_valid"),
        ),
        sa.CheckConstraint(
            "to_status IN ('active', 'reserved', 'sold', 'removed', 'unknown')",
            name=op.f("ck_listing_status_history_to_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_status_history_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_status_history")),
    )
    op.create_index(
        op.f("ix_listing_status_history_listing_id"),
        "listing_status_history",
        ["listing_id"],
        unique=False,
    )
    op.create_table(
        "price_history",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("previous_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "currency IS NULL OR currency ~ '^[A-Z]{3}$'",
            name=op.f("ck_price_history_currency_iso"),
        ),
        sa.CheckConstraint("price > 0", name=op.f("ck_price_history_price_positive")),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_price_history_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_history")),
        sa.UniqueConstraint(
            "listing_id", "observed_at", name=op.f("uq_price_history_listing_id_observed_at")
        ),
    )
    op.create_index(
        "ix_price_history_listing_observed",
        "price_history",
        ["listing_id", sa.literal_column("observed_at DESC")],
        unique=False,
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("evaluation_id", sa.BigInteger(), nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "channel", sa.String(length=16), server_default=sa.text("'telegram'"), nullable=False
        ),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("external_message_id", sa.BigInteger(), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_decision", sa.String(length=16), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("channel IN ('telegram')", name=op.f("ck_alerts_channel_valid")),
        sa.CheckConstraint(
            "priority IN ('high', 'normal', 'review', 'info')",
            name=op.f("ck_alerts_priority_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'failed', 'suppressed')",
            name=op.f("ck_alerts_status_valid"),
        ),
        sa.CheckConstraint(
            "user_decision IS NULL OR user_decision IN ('buy', 'pass', 'review')",
            name=op.f("ck_alerts_user_decision_valid"),
        ),
        sa.CheckConstraint(
            "attempts IS NULL OR attempts >= 0", name=op.f("ck_alerts_attempts_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
            name=op.f("fk_alerts_decided_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["listing_evaluations.id"],
            name=op.f("fk_alerts_evaluation_id_listing_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_alerts_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint(
            "evaluation_id", "channel", name=op.f("uq_alerts_evaluation_id_channel")
        ),
    )
    op.create_index(op.f("ix_alerts_listing_id"), "alerts", ["listing_id"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_table(
        "purchases",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=True),
        sa.Column("alert_id", sa.BigInteger(), nullable=True),
        sa.Column("evaluation_id", sa.BigInteger(), nullable=True),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("seller_id", sa.BigInteger(), nullable=True),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("purchase_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "buyer_protection_fee",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "inbound_shipping",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "other_acquisition_costs",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("total_acquisition_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("item_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency IS NULL OR currency ~ '^[A-Z]{3}$'", name=op.f("ck_purchases_currency_iso")
        ),
        sa.CheckConstraint(
            "buyer_protection_fee IS NULL OR buyer_protection_fee >= 0",
            name=op.f("ck_purchases_buyer_protection_fee_non_negative"),
        ),
        sa.CheckConstraint(
            "inbound_shipping IS NULL OR inbound_shipping >= 0",
            name=op.f("ck_purchases_inbound_shipping_non_negative"),
        ),
        sa.CheckConstraint("item_count >= 1", name=op.f("ck_purchases_item_count_positive")),
        sa.CheckConstraint(
            "other_acquisition_costs IS NULL OR other_acquisition_costs >= 0",
            name=op.f("ck_purchases_other_acquisition_costs_non_negative"),
        ),
        sa.CheckConstraint(
            "purchase_price IS NULL OR purchase_price >= 0",
            name=op.f("ck_purchases_purchase_price_non_negative"),
        ),
        sa.CheckConstraint(
            "total_acquisition_cost = purchase_price + buyer_protection_fee + inbound_shipping + other_acquisition_costs",
            name=op.f("ck_purchases_total_is_sum"),
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
            name=op.f("fk_purchases_alert_id_alerts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_purchases_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["listing_evaluations.id"],
            name=op.f("fk_purchases_evaluation_id_listing_evaluations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_purchases_listing_id_listings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["marketplace"],
            ["marketplaces.code"],
            name=op.f("fk_purchases_marketplace_marketplaces"),
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["sellers.id"],
            name=op.f("fk_purchases_seller_id_sellers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchases")),
    )
    op.create_index(op.f("ix_purchases_listing_id"), "purchases", ["listing_id"], unique=False)
    op.create_table(
        "inventory_items",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("purchase_id", sa.BigInteger(), nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=True),
        sa.Column("product_id", sa.BigInteger(), nullable=True),
        sa.Column("brand_id", sa.BigInteger(), nullable=True),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("size_normalised", sa.String(length=10), nullable=True),
        sa.Column("colour", sa.String(length=30), nullable=True),
        sa.Column("condition_on_receipt", sa.String(length=20), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("allocated_acquisition_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "cleaning_cost",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "repair_cost",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "other_costs",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("expected_resale_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expected_profit", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'ordered'"), nullable=False
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("listed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("listed_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("listing_channel", sa.String(length=32), nullable=True),
        sa.Column("listing_url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition_on_receipt IS NULL OR condition_on_receipt IN ('new_with_tags', 'new_without_tags', 'very_good', 'good', 'satisfactory')",
            name=op.f("ck_inventory_items_condition_on_receipt_valid"),
        ),
        sa.CheckConstraint(
            "currency IS NULL OR currency ~ '^[A-Z]{3}$'",
            name=op.f("ck_inventory_items_currency_iso"),
        ),
        sa.CheckConstraint(
            "status IN ('ordered', 'in_transit', 'received', 'needs_work', 'ready_to_list', 'listed', 'sold', 'shipped', 'completed', 'returned', 'written_off')",
            name=op.f("ck_inventory_items_status_valid"),
        ),
        sa.CheckConstraint(
            "allocated_acquisition_cost IS NULL OR allocated_acquisition_cost >= 0",
            name=op.f("ck_inventory_items_allocated_acquisition_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "cleaning_cost IS NULL OR cleaning_cost >= 0",
            name=op.f("ck_inventory_items_cleaning_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "listed_price IS NULL OR listed_price >= 0",
            name=op.f("ck_inventory_items_listed_price_non_negative"),
        ),
        sa.CheckConstraint(
            "other_costs IS NULL OR other_costs >= 0",
            name=op.f("ck_inventory_items_other_costs_non_negative"),
        ),
        sa.CheckConstraint(
            "repair_cost IS NULL OR repair_cost >= 0",
            name=op.f("ck_inventory_items_repair_cost_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_inventory_items_brand_id_brands"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_inventory_items_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_inventory_items_listing_id_listings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_items_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchases.id"],
            name=op.f("fk_inventory_items_purchase_id_purchases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_items")),
    )
    op.create_index(
        "ix_inventory_items_brand_category",
        "inventory_items",
        ["brand_id", "category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_items_purchase_id"), "inventory_items", ["purchase_id"], unique=False
    )
    op.create_index(op.f("ix_inventory_items_status"), "inventory_items", ["status"], unique=False)
    op.create_table(
        "inventory_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("inventory_item_id", sa.BigInteger(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "from_status IS NULL OR from_status IN ('ordered', 'in_transit', 'received', 'needs_work', 'ready_to_list', 'listed', 'sold', 'shipped', 'completed', 'returned', 'written_off')",
            name=op.f("ck_inventory_events_from_status_valid"),
        ),
        sa.CheckConstraint(
            "to_status IN ('ordered', 'in_transit', 'received', 'needs_work', 'ready_to_list', 'listed', 'sold', 'shipped', 'completed', 'returned', 'written_off')",
            name=op.f("ck_inventory_events_to_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_inventory_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_inventory_events_inventory_item_id_inventory_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_events")),
    )
    op.create_index(
        op.f("ix_inventory_events_inventory_item_id"),
        "inventory_events",
        ["inventory_item_id"],
        unique=False,
    )
    op.create_table(
        "market_sales",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.Column("marketplace", sa.String(length=32), nullable=True),
        sa.Column("listing_id", sa.BigInteger(), nullable=True),
        sa.Column("inventory_item_id", sa.BigInteger(), nullable=True),
        sa.Column("product_id", sa.BigInteger(), nullable=True),
        sa.Column("brand_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("size_normalised", sa.String(length=10), nullable=True),
        sa.Column("colour", sa.String(length=30), nullable=True),
        sa.Column("condition", sa.String(length=20), nullable=True),
        sa.Column("sale_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price_type", sa.String(length=32), nullable=False),
        sa.Column("listed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sold_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("days_to_sale", sa.Integer(), nullable=True),
        sa.Column(
            "trust_weight",
            sa.Numeric(precision=4, scale=3),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "match_confidence",
            sa.Numeric(precision=4, scale=3),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("is_outlier", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("excluded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("excluded_reason", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition IS NULL OR condition IN ('new_with_tags', 'new_without_tags', 'very_good', 'good', 'satisfactory')",
            name=op.f("ck_market_sales_condition_valid"),
        ),
        sa.CheckConstraint(
            "currency IS NULL OR currency ~ '^[A-Z]{3}$'", name=op.f("ck_market_sales_currency_iso")
        ),
        sa.CheckConstraint(
            "price_type IN ('final_sale_price', 'last_asking_price')",
            name=op.f("ck_market_sales_price_type_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('own_sale', 'manual_entry', 'csv_import', 'observed_sold_listing', 'licensed_api')",
            name=op.f("ck_market_sales_source_valid"),
        ),
        sa.CheckConstraint(
            "days_to_sale IS NULL OR days_to_sale >= 0",
            name=op.f("ck_market_sales_days_to_sale_non_negative"),
        ),
        sa.CheckConstraint(
            "listed_at IS NULL OR listed_at <= sold_at",
            name=op.f("ck_market_sales_listed_before_sold"),
        ),
        sa.CheckConstraint(
            "match_confidence IS NULL OR (match_confidence >= 0 AND match_confidence <= 1)",
            name=op.f("ck_market_sales_match_confidence_range"),
        ),
        sa.CheckConstraint("sale_price > 0", name=op.f("ck_market_sales_sale_price_positive")),
        sa.CheckConstraint(
            "trust_weight IS NULL OR (trust_weight >= 0 AND trust_weight <= 1)",
            name=op.f("ck_market_sales_trust_weight_range"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_market_sales_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_market_sales_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_market_sales_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_market_sales_inventory_item_id_inventory_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_market_sales_listing_id_listings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["marketplace"],
            ["marketplaces.code"],
            name=op.f("fk_market_sales_marketplace_marketplaces"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_market_sales_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_sales")),
        sa.UniqueConstraint("source", "source_ref", name=op.f("uq_market_sales_source_source_ref")),
    )
    op.create_index(
        "ix_market_sales_brand_category_sold",
        "market_sales",
        ["brand_id", "category_id", sa.literal_column("sold_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_sales_category_id"), "market_sales", ["category_id"], unique=False
    )
    op.create_index(
        "ix_market_sales_product_size_condition",
        "market_sales",
        ["product_id", "size_normalised", "condition"],
        unique=False,
    )
    op.create_index(
        "ix_market_sales_product_sold",
        "market_sales",
        ["product_id", sa.literal_column("sold_at DESC")],
        unique=False,
    )
    op.create_table(
        "prediction_results",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("inventory_item_id", sa.BigInteger(), nullable=False),
        sa.Column("evaluation_id", sa.BigInteger(), nullable=True),
        sa.Column("model_version", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("predicted_quick_sale", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("predicted_expected_sale", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("predicted_optimistic_sale", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("predicted_profit", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("predicted_roi", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("predicted_days_to_sale", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("predicted_comp_sample_size", sa.Integer(), nullable=True),
        sa.Column("predicted_comp_level", sa.String(length=8), nullable=True),
        sa.Column(
            "predicted_from_price_guide",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("actual_sale_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("actual_profit", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("actual_roi", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("actual_days_to_sale", sa.Integer(), nullable=True),
        sa.Column("price_error", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_error_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("actual_within_quick_optimistic", sa.Boolean(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "predicted_comp_level IS NULL OR predicted_comp_level IN ('L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'GUIDE')",
            name=op.f("ck_prediction_results_predicted_comp_level_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["listing_evaluations.id"],
            name=op.f("fk_prediction_results_evaluation_id_listing_evaluations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_prediction_results_inventory_item_id_inventory_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prediction_results")),
        sa.UniqueConstraint(
            "inventory_item_id", name=op.f("uq_prediction_results_inventory_item_id")
        ),
    )
    op.create_table(
        "resales",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("inventory_item_id", sa.BigInteger(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("sold_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("sale_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "selling_fees",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "outbound_shipping_cost",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "shipping_charged_to_buyer",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "refunds",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "other_selling_costs",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("net_proceeds", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paid_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("market_sale_id", sa.BigInteger(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency IS NULL OR currency ~ '^[A-Z]{3}$'", name=op.f("ck_resales_currency_iso")
        ),
        sa.CheckConstraint(
            "net_proceeds = sale_price + shipping_charged_to_buyer - selling_fees - outbound_shipping_cost - refunds - other_selling_costs",
            name=op.f("ck_resales_net_is_sum"),
        ),
        sa.CheckConstraint(
            "other_selling_costs IS NULL OR other_selling_costs >= 0",
            name=op.f("ck_resales_other_selling_costs_non_negative"),
        ),
        sa.CheckConstraint(
            "outbound_shipping_cost IS NULL OR outbound_shipping_cost >= 0",
            name=op.f("ck_resales_outbound_shipping_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "refunds IS NULL OR refunds >= 0", name=op.f("ck_resales_refunds_non_negative")
        ),
        sa.CheckConstraint("sale_price > 0", name=op.f("ck_resales_sale_price_positive")),
        sa.CheckConstraint(
            "selling_fees IS NULL OR selling_fees >= 0",
            name=op.f("ck_resales_selling_fees_non_negative"),
        ),
        sa.CheckConstraint(
            "shipping_charged_to_buyer IS NULL OR shipping_charged_to_buyer >= 0",
            name=op.f("ck_resales_shipping_charged_to_buyer_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_resales_inventory_item_id_inventory_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["market_sale_id"],
            ["market_sales.id"],
            name=op.f("fk_resales_market_sale_id_market_sales"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resales")),
        sa.UniqueConstraint("inventory_item_id", name=op.f("uq_resales_inventory_item_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resales")
    op.drop_table("prediction_results")
    op.drop_index("ix_market_sales_product_sold", table_name="market_sales")
    op.drop_index("ix_market_sales_product_size_condition", table_name="market_sales")
    op.drop_index(op.f("ix_market_sales_category_id"), table_name="market_sales")
    op.drop_index("ix_market_sales_brand_category_sold", table_name="market_sales")
    op.drop_table("market_sales")
    op.drop_index(op.f("ix_inventory_events_inventory_item_id"), table_name="inventory_events")
    op.drop_table("inventory_events")
    op.drop_index(op.f("ix_inventory_items_status"), table_name="inventory_items")
    op.drop_index(op.f("ix_inventory_items_purchase_id"), table_name="inventory_items")
    op.drop_index("ix_inventory_items_brand_category", table_name="inventory_items")
    op.drop_table("inventory_items")
    op.drop_index(op.f("ix_purchases_listing_id"), table_name="purchases")
    op.drop_table("purchases")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_listing_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_price_history_listing_observed", table_name="price_history")
    op.drop_table("price_history")
    op.drop_index(op.f("ix_listing_status_history_listing_id"), table_name="listing_status_history")
    op.drop_table("listing_status_history")
    op.drop_index(op.f("ix_listing_images_phash"), table_name="listing_images")
    op.drop_index(op.f("ix_listing_images_listing_id"), table_name="listing_images")
    op.drop_table("listing_images")
    op.drop_index("ix_listing_evaluations_listing_evaluated", table_name="listing_evaluations")
    op.drop_index("ix_listing_evaluations_decision_evaluated", table_name="listing_evaluations")
    op.drop_table("listing_evaluations")
    op.drop_index("ix_ai_requests_hash_purpose", table_name="ai_requests")
    op.drop_table("ai_requests")
    op.drop_index(op.f("ix_product_aliases_product_id"), table_name="product_aliases")
    op.drop_index(op.f("ix_product_aliases_alias_normalised"), table_name="product_aliases")
    op.drop_table("product_aliases")
    op.drop_index(
        "uq_market_statistics_scope",
        table_name="market_statistics",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_table("market_statistics")
    op.drop_index("ix_listings_status_first_seen", table_name="listings")
    op.drop_index(op.f("ix_listings_seller_id"), table_name="listings")
    op.drop_index(op.f("ix_listings_matched_product_id"), table_name="listings")
    op.drop_index(op.f("ix_listings_category_id"), table_name="listings")
    op.drop_index("ix_listings_brand_category", table_name="listings")
    op.drop_index(
        "ix_listings_active_first_seen",
        table_name="listings",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("listings")
    op.drop_table("sellers")
    op.drop_index(
        "uq_products_generic_per_brand_category",
        table_name="products",
        postgresql_where=sa.text("level = 'brand_category_generic'"),
    )
    op.drop_index(
        "uq_products_brand_model_code",
        table_name="products",
        postgresql_where=sa.text("model_code IS NOT NULL"),
    )
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_index("ix_products_brand_category", table_name="products")
    op.drop_table("products")
    op.drop_table("ingestion_runs")
    op.drop_index(op.f("ix_category_aliases_category_id"), table_name="category_aliases")
    op.drop_table("category_aliases")
    op.drop_index(op.f("ix_brand_aliases_brand_id"), table_name="brand_aliases")
    op.drop_index(op.f("ix_brand_aliases_alias_normalised"), table_name="brand_aliases")
    op.drop_table("brand_aliases")
    op.drop_index("ix_audit_log_entity", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("users")
    op.drop_table("task_failures")
    op.drop_table("marketplaces")
    op.drop_table("fx_rates")
    op.drop_index(
        "uq_config_versions_one_active",
        table_name="config_versions",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("config_versions")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_table("brands")
    op.drop_index(op.f("ix_bot_state_expires_at"), table_name="bot_state")
    op.drop_table("bot_state")
    # ### end Alembic commands ###
